resolver: nightly-2017-04-01
packages:
- '.'
extra-deps:
- cabal-doctest-1.0.2
ghc-options:
  "*": -DCALLCONV=ccall
nix:
  packages: [ ncurses ]

# XXX workaround
# https://github.com/commercialhaskell/stack/issues/2245
hide-th-loading: false
