# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.2 2002/06/20 16:12:32 simonmar Exp $

TOP=../..
include $(TOP)/mk/boilerplate.mk

H_FILES = $(wildcard *.h)

includedir = $(libdir)/include
INSTALL_INCLUDES = $(H_FILES)

include $(TOP)/mk/target.mk
